### ISSUE TITLE
Can it be updated to support dragging and dropping into comfyui and reading metadata?

### ISSUE THREAD

**Issue by 3349593383** [hayden-fr/ComfyUI-Image-Browsing#11]
![image](https://github.com/user-attachments/assets/50d2f273-b6b5-4e8f-a2c4-2b283982251f)
![屏幕截图 2024-12-24 140322](https://github.com/user-attachments/assets/e126e3a8-020e-499c-841e-6a433c4d9a50)

**Comment by hayden-cn** [comment]
ok
