### ISSUE TITLE
How do you use this?

### ISSUE THREAD

**Issue by sebas1111111** [hayden-fr/ComfyUI-Image-Browsing#3]
What does this do?

**Comment by Malaombra** [comment]
i'm wondering as well...

**Comment by coralsaw** [comment]
Creates an "output" button in the ComfyUI dialog panel, that displays in a gallery all your pics in the "output" folder.

**Comment by rafstahelin** [comment]
> Creates an "output" button in the ComfyUI dialog panel, that displays in a gallery all your pics in the "output" folder.

i dont actually see this button. Where is it? Its not in the dialog panel as far as i can see
