### ISSUE TITLE
does not work with new style menue

### ISSUE THREAD

**Issue by speters** [hayden-fr/ComfyUI-Image-Browsing#6]
Thx for this extension.

Unfortunately, this does not work with the [new menue bar](https://github.com/comfyanonymous/ComfyUI/pull/3112).

See screenshots:

"output" (image browsing) button visible on old side bar:
![Screenshot 2024-07-08 at 18-03-38 ComfyUI](https://github.com/hayden-fr/ComfyUI-Image-Browsing/assets/1384994/77962f36-0c9e-4473-a8a0-3eab38bf9784)

No "output" (image browsing) button on new menue bar:
![Screenshot 2024-07-08 at 18-04-14 ComfyUI](https://github.com/hayden-fr/ComfyUI-Image-Browsing/assets/1384994/67df266c-66a9-4c49-9a96-7d3d2435d7af)

**Comment by hayden-cn** [comment]
Thanks for feedback, I will repair as soon as possible.

**Comment by speters** [comment]
Thx for this!

The SVG approach is great, as it allows a dedicated icon.
But the size of the button appears not quite right on my display.
![Screenshot_20240715-122459](https://github.com/user-attachments/assets/e3202bf3-53fd-4343-80b8-b645fcebf6d0)

There are similar icons in the [material design icon package](https://pictogrammers.com/library/mdi/icon/folder-multiple-image/) which is used in ComfyUI, so it could be as simple as:
![Screenshot_20240715-123652](https://github.com/user-attachments/assets/b548e07b-5658-4530-bc66-0036714adfbb)
