### ISSUE TITLE
The interface has issues after the update.

### ISSUE THREAD

**Issue by inorsis** [hayden-fr/ComfyUI-Image-Browsing#9]
The delete and download icons are missing, and clicking on an image opens it automatically without allowing selection. The file name and image overlap after the update.
![截圖 2024-11-14 下午1 43 47](https://github.com/user-attachments/assets/0de35de2-3cf9-4619-8025-656e6c204590)

**Comment by hayden-cn** [comment]
The feature migration is in progress. If you urgently need the delete and download feature, you can temporarily fall back to tag v1.0.0.

For the problem of the file name and image overlap, I had fixed it on latest version. If you are on the latest version, I think I'll need some time to look up how this problem occurs.

**Comment by inorsis** [comment]
thanks for the reply and your hardwork,i love this custom node, i can manage images easily through cloud service for comfyui.
the problem of the file name and image overlap only happens in root output folder, it looks good under subfolder.

**Comment by hayden-cn** [comment]
I'm glad you like the extension, and thanks for the information, I'll fix it as soon as possible.
